[StagingDefinition = [Kind = "FastCopy"]]
section Section1;
[DataDestinations = {[Definition = [Kind = "Reference", QueryName = "dimcustomerwdr_DataDestination", IsNewTarget = false], Settings = [Kind = "Manual", AllowCreation = false, ColumnSettings = [Mappings = {[SourceColumnName = "CustomerKey", DestinationColumnName = "CustomerKey"], [SourceColumnName = "GeographyKey", DestinationColumnName = "GeographyKey"], [SourceColumnName = "CustomerAlternateKey", DestinationColumnName = "CustomerAlternateKey"], [SourceColumnName = "Title", DestinationColumnName = "Title"], [SourceColumnName = "First Name", DestinationColumnName = "First Name"], [SourceColumnName = "Middle Name", DestinationColumnName = "Middle Name"], [SourceColumnName = "Last Name", DestinationColumnName = "Last Name"], [SourceColumnName = "Name Style", DestinationColumnName = "Name Style"], [SourceColumnName = "Birth Date", DestinationColumnName = "Birth Date"], [SourceColumnName = "Marital Status", DestinationColumnName = "Marital Status"], [SourceColumnName = "Suffix", DestinationColumnName = "Suffix"], [SourceColumnName = "Gender", DestinationColumnName = "Gender"], [SourceColumnName = "Email Address", DestinationColumnName = "Email Address"], [SourceColumnName = "Yearly Income", DestinationColumnName = "Yearly Income"], [SourceColumnName = "Total Children", DestinationColumnName = "Total Children"], [SourceColumnName = "Number Children At Home", DestinationColumnName = "Number Children At Home"], [SourceColumnName = "English Education", DestinationColumnName = "English Education"], [SourceColumnName = "Spanish Education", DestinationColumnName = "Spanish Education"], [SourceColumnName = "FrenchEducation", DestinationColumnName = "FrenchEducation"], [SourceColumnName = "English Occupation", DestinationColumnName = "English Occupation"], [SourceColumnName = "Spanish Occupation", DestinationColumnName = "Spanish Occupation"], [SourceColumnName = "FrenchOccupation", DestinationColumnName = "FrenchOccupation"], [SourceColumnName = "HouseOwnerFlag", DestinationColumnName = "HouseOwnerFlag"], [SourceColumnName = "Number Cars Owned", DestinationColumnName = "Number Cars Owned"], [SourceColumnName = "Address Line 1", DestinationColumnName = "Address Line 1"], [SourceColumnName = "Address Line 2", DestinationColumnName = "Address Line 2"], [SourceColumnName = "Phone", DestinationColumnName = "Phone"], [SourceColumnName = "Date First Purchase", DestinationColumnName = "Date First Purchase"], [SourceColumnName = "Commute Distance", DestinationColumnName = "Commute Distance"]}], DynamicSchema = false, UpdateMethod = [Kind = "Replace"], TypeSettings = [Kind = "Table"]]]}]
shared dimcustomerwdr = let
  Source = Lakehouse.Contents(null),
  Navigation = Source{[workspaceId = "7068e8ef-4071-4b46-9ed6-bd13210ed606"]}[Data],
  #"Navigation 1" = Navigation{[lakehouseId = "7afa7a75-8388-4595-a772-43fa62652d44"]}[Data],
  #"Navigation 2" = #"Navigation 1"{[Id = "dimcustomerwdr", ItemKind = "Table"]}[Data],
  #"Renamed columns" = Table.RenameColumns(#"Navigation 2", {{"FirstName", "First Name"}, {"MiddleName", "Middle Name"}, {"LastName", "Last Name"}, {"NameStyle", "Name Style"}, {"BirthDate", "Birth Date"}, {"MaritalStatus", "Marital Status"}, {"EmailAddress", "Email Address"}, {"YearlyIncome", "Yearly Income"}, {"TotalChildren", "Total Children"}, {"NumberChildrenAtHome", "Number Children At Home"}, {"EnglishEducation", "English Education"}, {"SpanishEducation", "Spanish Education"}, {"EnglishOccupation", "English Occupation"}, {"SpanishOccupation", "Spanish Occupation"}, {"NumberCarsOwned", "Number Cars Owned"}, {"AddressLine1", "Address Line 1"}, {"AddressLine2", "Address Line 2"}, {"DateFirstPurchase", "Date First Purchase"}, {"CommuteDistance", "Commute Distance"}})
in
  #"Renamed columns";
shared dimcustomerwdr_DataDestination = let
  Pattern = Fabric.Warehouse([CreateNavigationProperties = false]),
  Navigation_1 = Pattern{[workspaceId = "7068e8ef-4071-4b46-9ed6-bd13210ed606"]}[Data],
  Navigation_2 = Navigation_1{[warehouseId = "9c1d3800-7998-4d5f-b0fc-634d04693c20"]}[Data],
  TableNavigation = Navigation_2{[Schema = "dbo", Item = "dimcustomer"]}[Data]
in
  TableNavigation;
