CREATE TABLE [dbo].[dimcustomer] (

	[CustomerKey] int NULL, 
	[GeographyKey] int NULL, 
	[CustomerAlternateKey] varchar(8000) NULL, 
	[Title] varchar(8000) NULL, 
	[First Name] varchar(8000) NULL, 
	[Middle Name] varchar(8000) NULL, 
	[Last Name] varchar(8000) NULL, 
	[Name Style] bit NULL, 
	[Birth Date] date NULL, 
	[Marital Status] varchar(8000) NULL, 
	[Suffix] varchar(8000) NULL, 
	[Gender] varchar(8000) NULL, 
	[Email Address] varchar(8000) NULL, 
	[Yearly Income] decimal(38,6) NULL, 
	[Total Children] smallint NULL, 
	[Number Children At Home] smallint NULL, 
	[English Education] varchar(8000) NULL, 
	[Spanish Education] varchar(8000) NULL, 
	[FrenchEducation] varchar(8000) NULL, 
	[English Occupation] varchar(8000) NULL, 
	[Spanish Occupation] varchar(8000) NULL, 
	[FrenchOccupation] varchar(8000) NULL, 
	[HouseOwnerFlag] varchar(8000) NULL, 
	[Number Cars Owned] smallint NULL, 
	[Address Line 1] varchar(8000) NULL, 
	[Address Line 2] varchar(8000) NULL, 
	[Phone] varchar(8000) NULL, 
	[Date First Purchase] date NULL, 
	[Commute Distance] varchar(8000) NULL
);