CREATE TABLE [dbo].[dimproduct] (

	[ProductKey] int NULL, 
	[ProductAlternateKey] varchar(8000) NULL, 
	[ProductSubcategoryKey] int NULL, 
	[Weight Unit Measure Code] varchar(8000) NULL, 
	[Size Unit Measure Code] varchar(8000) NULL, 
	[Product Name] varchar(8000) NULL, 
	[SpanishProductName] varchar(8000) NULL, 
	[FrenchProductName] varchar(8000) NULL, 
	[Standard Cost] decimal(38,6) NULL, 
	[FinishedGoodsFlag] bit NULL, 
	[Color] varchar(8000) NULL, 
	[SafetyStockLevel] smallint NULL, 
	[ReorderPoint] smallint NULL, 
	[List Price] decimal(38,6) NULL, 
	[Size] varchar(8000) NULL, 
	[Size Range] varchar(8000) NULL, 
	[Weight] float NULL, 
	[DaysToManufacture] int NULL, 
	[ProductLine] varchar(8000) NULL, 
	[Dealer Price] decimal(38,6) NULL, 
	[Class] varchar(8000) NULL, 
	[Style] varchar(8000) NULL, 
	[Model Name] varchar(8000) NULL, 
	[EnglishDescription] varchar(8000) NULL, 
	[FrenchDescription] varchar(8000) NULL, 
	[ChineseDescription] varchar(8000) NULL, 
	[ArabicDescription] varchar(8000) NULL, 
	[HebrewDescription] varchar(8000) NULL, 
	[ThaiDescription] varchar(8000) NULL, 
	[GermanDescription] varchar(8000) NULL, 
	[JapaneseDescription] varchar(8000) NULL, 
	[TurkishDescription] varchar(8000) NULL, 
	[StartDate] datetime2(6) NULL, 
	[EndDate] datetime2(6) NULL, 
	[Status] varchar(8000) NULL
);