CREATE TABLE [dbo].[factinternetsales] (

	[ProductKey] int NULL, 
	[OrderDateKey] int NULL, 
	[DueDateKey] int NULL, 
	[ShipDateKey] int NULL, 
	[CustomerKey] int NULL, 
	[PromotionKey] int NULL, 
	[CurrencyKey] int NULL, 
	[SalesTerritoryKey] int NULL, 
	[Sales Order Number] varchar(8000) NULL, 
	[Sales Order Line Number] smallint NULL, 
	[RevisionNumber] smallint NULL, 
	[Order Quantity] smallint NULL, 
	[Unit Price] decimal(38,6) NULL, 
	[Extended Amount] decimal(38,6) NULL, 
	[UnitPrice Discount Pct] float NULL, 
	[Discount Amount] float NULL, 
	[Product Standard Cost] decimal(38,6) NULL, 
	[Total Product Cost] decimal(38,6) NULL, 
	[Sales Amount] decimal(38,6) NULL, 
	[Tax Amt] decimal(38,6) NULL, 
	[Freight] decimal(38,6) NULL, 
	[CarrierTrackingNumber] varchar(8000) NULL, 
	[CustomerPONumber] varchar(8000) NULL, 
	[Order Date] datetime2(6) NULL, 
	[Due Date] datetime2(6) NULL, 
	[Ship Date] datetime2(6) NULL
);